# ============================================
# BFF Service Configuration (from Config Server)
# ============================================

server:
  port: 8080

spring:
  application:
    name: bff-service

# ============================================
# Service URLs (Centrally Managed)
# ============================================
customer:
  service:
    url: http://localhost:8081

policy:
  service:
    url: http://localhost:8085

# Data Pipeline Service (Consolidated: Ingestion + Metadata + Processing + Matching)
data-pipeline:
  service:
    url: http://localhost:8082

ingestion:
  service:
    url: http://localhost:8082

metadata:
  service:
    url: http://localhost:8082

processing:
  service:
    url: http://localhost:8082

# ============================================
# Feign Configuration
# ============================================
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: BASIC

# ============================================
# Security
# ============================================
# JWT configuration (if needed)
# jwt:
#   secret: your-secret-key-from-config-server
#   expiration: 86400000

# ============================================
# Logging
# ============================================
logging:
  level:
    com.mypolicy.bff: DEBUG
    feign: DEBUG

# ============================================
# Actuator
# ============================================
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
