# ============================================
# Data-Pipeline Service Configuration (from Config Server)
# Consolidated: Ingestion + Metadata + Processing + Matching
# ============================================

server:
  port: 8082

spring:
  application:
    name: data-pipeline-service

  # ============================================
  # PostgreSQL Configuration (Metadata Module)
  # ============================================
  datasource:
    url: jdbc:postgresql://localhost:5432/mypolicy_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # ============================================
  # MongoDB Configuration (Ingestion Module)
  # ============================================
  data:
    mongodb:
      uri: mongodb://localhost:27017/ingestion_db
      auto-index-creation: true

# ============================================
# External Services (Feign Clients)
# ============================================
customer:
  service:
    url: http://localhost:8081

policy:
  service:
    url: http://localhost:8085

# ============================================
# Module-Specific Settings
# ============================================
ingestion:
  storage:
    path: storage/ingestion
  max-file-size: 52428800
  allowed-extensions: .xls,.xlsx,.csv

metadata:
  cache:
    ttl: 3600
    max-size: 1000

processing:
  thread-pool-size: 10
  batch-size: 100

matching:
  fuzzy-threshold: 3
  similarity-algorithm: LEVENSHTEIN

# ============================================
# Feign Configuration
# ============================================
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

# ============================================
# Logging
# ============================================
logging:
  level:
    com.mypolicy.pipeline: INFO
    com.mypolicy.pipeline.ingestion: DEBUG
    com.mypolicy.pipeline.metadata: DEBUG
    com.mypolicy.pipeline.processing: DEBUG
    com.mypolicy.pipeline.matching: DEBUG

# ============================================
# Actuator
# ============================================
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
